### ISSUE TITLE
fix: Default to system skin 

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/sx-monorepo#117]
Currently, the UI defaults to dark mode and doesn't consider the system's theme settings. We should first check the system theme, then look for the user's preference in localStorage. If neither is set, we should default to dark mode.

**Comment by Sekhmet** [comment]
@bonustrack @samuveth 

From previous discussion:
> I'm fine moving back to OS preference or fallback to dark if no pref

The issue is that `prefers-color-scheme` doesn't support no preference setting (it's either light or dark, and light is default - there was no-preference value but was deprecated and removed).

> [light](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme#light)
Indicates that user has notified that they prefer an interface that has a light theme, or **has not expressed an active preference**.

Because of this we can't tell if OS reports `light` preference because of actual user preference or if it's not supported by OS, so it's impossible to have default dark theme while also respecting OS preferences.

So we either respect OS settings (meaning that users that haven't set theme explicitly will get light theme) or we don't respect it at all.

If we decide to ignore this because of this limitation I will just refactor `useUserSkin` to use composables from vue use, while keeping current behaviour.
