### ISSUE TITLE
feat: support comma syntax for whitelist strategy

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#121]
On the whitelist strategy we should allow for comma as separator of addresses. Currently it seem that using comma break space creation (reported by Yuki)

**Comment by Sekhmet** [comment]
We should also validate the format is correct so it doesn't break space creation (right now if I put invalid format it will most likely result in failure in space creation (and if not result in broken space)).

**Comment by wa0x6e** [comment]
Are we talking about this input, which appear only at 2 places: Voting strategies and proposal validation ?

![Image](https://github.com/snapshot-labs/sx-monorepo/assets/495709/428eef89-6623-470d-82d9-95644e1d5c8a)

**Comment by Sekhmet** [comment]
Yes, in proposal validation it's pretty much the same thing (because it wraps voting strategies as well).

It's in two places (for Starknet and Ethereum):
https://github.com/snapshot-labs/sx-monorepo/blob/8e0cdd275ca500f9c14e8b12e44106636b7d7509/apps/ui/src/networks/evm/constants.ts#L205-L216
https://github.com/snapshot-labs/sx-monorepo/blob/ef7b2789d492aab0c0dcd51d153a1daf69856386/apps/ui/src/networks/starknet/constants.ts#L253-L267

So we need to validate format and parse it in those two places.
I think we should create some custom format for validation.
Also I'd say we should allow either comma or colon, not both mixed at the same time.
