### ISSUE TITLE
refactor: rename modal components

### ISSUE THREAD

**Issue by samuveth** [snapshot-labs/sx-monorepo#33]
I would like to deprecate the `/Modal` folder and rename the components as follows:
1. `Account` to `TopnavModalAccount`
2. `Delegate` to `SpaceDelegatesModalDelegate`
3. `DelegationConfig` to `FormProfileModalDelegationConfig`
4. `Drafts` to `EditorModalDrafts`
5. `EditContact` to `SettingsModalContact` For components that are coupled to a nested view e.g `Settings/Contacts` I think we should only include the parents name, in this case it's `Settings`. I think this better than including the child view because there can be multiple child views with the same name e.g there are two views called `Overview`. We could also include both parent and children but names could get long and I'm not sure it's worth it, let me know what you think @Sekhmet. I also removed the `Edit` because it's actually doing both add and edit.
7. `EditSpace` to `SpaceModalEditSpace` same here as point 5, actually it's `SpaceOverview`
8. `EditStrategy` to `ModalEditStrategy`
9. `PendingTransactions` to `IndicatorPendingTransactionsModal`
10. `SendNft` to `ModalSendNft`
11. `SendToken` to `ModalSendToken`
12. `Timeline` to `ModalProposalTimeline`
13. `Transaction` to `ModalTransactionBuilder`
14. `Votes` to `ProposalModalVotes` see point 5 explanation 
15. `VotingPower` to `IndicatorVotingPowerModal`

We could keep the `/Modal` folder as we do have a few widely used modal components but I'm not sure it's needed and I'd prefer not having it because it avoids developers getting confused and thinking that all modal components should be places in `/Modal`

**Comment by Sekhmet** [comment]
As mentioned before I kind of like the Modal being separate, because it's clear separation (similar as App/Ui, unlike Block) and with the amount of modals we have I feel like it makes sense to treat those as separate, global components (and all of those have standardised shape so they are designed to be used as plug-n-play component. To me modals are like `Ui` components, that we create to be as reusable as possible.

We are making a lot of changes in terms of structure, but to me we reached a point where we should start using it and see how the changes we made actually work and then use that experience to change more things with more familiarity.

What do you think?

**Comment by bonustrack** [comment]
Agree, Modal folder is clear separation we don't need to change much here. Looks much more confusing to me having it on the root folder.

**Comment by samuveth** [comment]
Ok I'm also fine with testing it as see how it goes, closing this for now then
