### ISSUE TITLE
bug(style): abstain icon on votes page should be gray

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#396]
Currently the abstain icon on the votes page for Highlight votes is not fully gray, the dash is using link color, we should fix that

https://testnet.snapshotx.xyz/#/sep:0x5559e6c038fD0494277ac85ab6576843A6d0187b/proposal/7/votes

<img width="1029" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/5acb5e75-93ad-41df-84fa-ec232f891fde">

**Comment by wa0x6e** [comment]
Also, in this proposal, why is the result empty, even though there are 2 votes ?
It leads to division by 0 in the voting power percentage


![Image](https://github.com/snapshot-labs/sx-monorepo/assets/495709/09076c39-954a-4932-865c-49318ebfb710)

**Comment by bonustrack** [comment]
These are offchain votes using Highlight, there might be an issue

**Comment by Sekhmet** [comment]
This is fixed by Highlight, we were mapping our votes wrong: https://github.com/snapshot-labs/highlight/pull/19

**Comment by Sekhmet** [comment]
> Also, in this proposal, why is the result empty, even though there are 2 votes ?
It leads to division by 0 in the voting power percentage

This space is misconfigured (it doesn't have Axiom executor strategy configured, but we forced some votes anyway), Highlight (API that processed Axiom votes) doesn't actually validate if you have VP so we can cast 0 VP votes, because there is no Axiom executor there is no quorum as well, so the math is broken.

Once we validate everything properly on Highlight it shouldn't be the case.
