### ISSUE TITLE
bug: proposal delay not working?

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#413]
I've created a proposal on a space having 5mn delay, but somehow the proposal was active directly after creating it, see here:
http://localhost:8080/#/sn-sep:0x03ffa8d9c48aa1208569af37292c9b0408496859803c9b7245172844e0c33745/proposal/2
http://localhost:8080/#/sn-sep:0x03ffa8d9c48aa1208569af37292c9b0408496859803c9b7245172844e0c33745/settings

<img width="480" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/dfeda726-d3be-428a-8e15-9c1cd9b3e359">

I was able to cast a vote before 5mn, this sound like issue may be at the contract level?

@pscott

**Comment by Sekhmet** [comment]
Looking at the [event](https://sepolia.starkscan.co/event/0x059712730ea7b7534ad556f0ca83a221ca5a22696e12a9f0b1c940720791e1e7_0).

Start timestamp is `1718792993000` `Wed Jun 19 2024 12:29:53 GMT+0200 (Central European Summer Time)` so UI seems to use what was broadcast.

Block time is `19 June 2024 at 12:24:53 CEST` so it was +5 minutes of delay.

**Comment by Sekhmet** [comment]
Timestamps at API are different for created (1718792938000) vs start (1718792993000) - 55s difference.

I'm not sure how [`info::get_block_timestamp()`](https://github.com/snapshot-labs/sx-starknet/blob/df4b6fd5d726fef6ff26044b28340119fe2fa341/starknet/src/space/space.cairo#L259C35-L260) works for yet unconfirmed transactions.

If blocks happen at 12:00, 12:05, 12:10 etc. and I send transaction at 12:09 what will be `get_block_timestamp`?

It looks like it would get timestamp of 12:05, instead of timestamp in the future, giving us this behaviour where optimistically indexed transactions could have start timestamp lower than created timestamp (for example when there is no voting delay).
Looks like this proposal got affected: https://testnet.snapshotx.xyz/#/sn-sep:0x01c63c00ce530de98ff6469bef06271231bc8a82ffc4122f9ec3ada7de23d68a/proposal/3


![Image](https://github.com/snapshot-labs/sx-monorepo/assets/1968722/f8bf69c3-f976-4290-803d-bc7c5e5627be)

**Comment by pscott** [comment]
@Sekhmet @bonustrack after double checking with Mirko from the [Pathfinder](https://github.com/eqlabs/pathfinder) team (Starknet node), they confirmed that the `get_block_timestamp()` syscall will refer to the "last" block timestamp. In your example @Sekhmet this would indeed be `10:05`.

This means that having a `voting_delay` smaller than the time it takes to create a block will indeed have no effects. I don't think it's a big issue (`voting_delay` should be ~ hours or days imho), but let me know if you think otherwise.
